services:
  - type: web
    name: rag-news-backend
    env: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LOG_LEVEL
        value: info
